### PR TITLE
Better `isES6Generator` check.

### PR DESCRIPTION
**Pull request by hemanth**
^

### CODE REVIEW

**Comment by bemson** [comment]
What your code gains in performance, is lost in quality. [Duck-typing](https://en.wikipedia.org/wiki/Duck_typing) is _not_ equal to comparing prototypes (via [instanceof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) or [isPrototypeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf)).

**Comment by hemanth** [comment]
Agree, but what be the senario where someone would have a non-generator function with `fn.constructor.name` as `GeneratorFunction`?

**Comment by bemson** [comment]
You just described it, @hemanth . We have a difference in principle around future-proof code. The project maintainers can decide if this risk is worth the reward.

**Comment by hemanth** [comment]
:+1:

**Comment by dtao** [comment]
@hemanth I really appreciate the contribution! In this case though I'm afraid I agree with @bemson. The likelihood of someone defining their own `GeneratorFunction` may be small, but it's certainly not nonexistent.

I won't claim to have a super-rigorous set of criteria for all design decisions in this library (it's grown to what it is now quite organically); but in this case since the proposed change could sometimes be wrong and doesn't (to my eye) bring much benefit, I'm going to have to decline.

Thanks again for the PR, though, and I hope this doesn't dissuade you from making more contributions in the future!

**Comment by hemanth** [comment]
I can get it, NP!

**Pull request closed without merging**
