### PR TITLE
Upgrade reverseArguments to handle functions of any arity

### PR DESCRIPTION
**Pull request by sjsyrek**
Uses library functions (map and reverse) to switch the arguments
around, making it possible to reverse the arguments of functions of any
arity instead of just binary functions.

### CODE REVIEW

**Comment by dtao** [comment]
Did you not read my comment?! ;)

In all seriousness, though, what's the intention behind this change? It's making an internal function more generic (and therefore slightly less efficient) without actually using it in that more generic way anywhere.

I don't mean to sound antagonistic. If you do have a use case in mind for this I'm happy to consider it. But otherwise, I'd have to go with [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) on this one.

**Comment by sjsyrek** [comment]
Yes, I read your comment! I just took it as a (personal) challenge, and an opportunity to solve a problem as an exercise. I heard your interview on the JS podcast, and the project sounded cool. And then DigitalOcean started this Hacktoberfest thing, so basically I was looking for projects to contribute to as a way of getting my feet wet. This is only my fourth ever pull request! If it's not useful, no need to accept it. I thought it might be, for the sake of making everything more generic (unknown future needs, etc.), but I can't claim to know exactly what the original function is for, precisely, so maybe it is unnecessary.

**Comment by dtao** [comment]
Nice work! Over a year has passed since our exchange so I'm guessing you've gained a decent amount of experience since opening this PR (it looks like it from your profile)!

As you probably sort of predicted, I don't intend to merge this PR as this _particular_ change isn't necessary for lazy.js. That said let me encourage you to continue to contribute, to this and other open source libraries.

Out of curiosity, looking back at this code, would you still write it the same way today? If you were to write a function that did the same thing now what would it look like?

**Comment by sjsyrek** [comment]
Yes, I have been busy!

If I were to rewrite the code today, I suppose I'd use some of the features of ES2015. Yours, for example:

`function reverseArguments(fn) {
       return function(x, y) { return fn(y, x); };
}`

I might write:

`const reverseArguments = fn => (x, y) => fn(y, x)`

Mine, I suppose I could do like this:

`const reverseArguments = fn => (...args) => fn(...args.reverse())`

But I can also understand if you find this style undesirable. I've been neck deep in Haskell lately, so everything I write has been terse, which isn't for everyone! What do you think?

**Pull request closed without merging**
